name: Token Yenileme

on:
  schedule:
    - cron: '0 * * * *'  # Hər saatda bir işləsin
  workflow_dispatch:  # Əl ilə də başlamaq üçün

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python token_yenile.py
